;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Sun Oct 6 2024
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================

DATA	SEGMENT
   PORTA EQU 0B0H
   PORTB EQU 0B2H
   PORTC EQU 0B4H
   COM_REG EQU 0B6H
DATA	ENDS

STK	SEGMENT STACK
   DW 200 DUP(?)
STK	ENDS

CODE    SEGMENT PUBLIC 'CODE'
        ASSUME CS:CODE, DS:DATA, SS:STK

	ORG 0000H
	
	XOR AX, AX
	XOR BX, BX
	XOR CX, CX
	XOR DX, DX
	
START:
   MOV DX, COM_REG
   MOV AL, 10000001B
   OUT DX, AL
   
   WAIT_INPUT:
      MOV DX, PORTC
      IN AL, DX
      CMP AL, 01H
      JE _ON_ALL
      CMP AL, 02H
      JE _UP_DOWN
      CMP AL, 04H
      JE _ZIG_ZAG
      CMP AL, 08H
      JE _ROTATE
      
      MOV AL, 00H
      MOV DX, PORTA
      OUT DX, AL
      
      JMP WAIT_INPUT
   
   _ON_ALL:
      MOV DX, PORTA
      MOV AL, 0FFH
      OUT DX, AL
      JMP WAIT_INPUT
   
   _UP_DOWN:
      MOV DX, PORTA
      MOV AL, 0FH
      OUT DX, AL
      NOT AL
      OUT DX, AL
      JMP WAIT_INPUT
   
   _ZIG_ZAG:
      MOV DX, PORTA
      MOV AL, 01010101B
      OUT DX, AL
      NOT AL
      OUT DX, AL
      JMP WAIT_INPUT
   
   _ROTATE:
      MOV AL, 01H
      PUSH AX

      _LOOP:
	 POP AX
	 
	 _CONT:
	 MOV DX, PORTA
	 OUT DX, AL
	 MOV CL, 01H
	 ROL AL, CL
	 PUSH AX
	 
	 MOV DX, PORTC
	 IN AL, DX
	 CMP AL, 08H
	 JE _LOOP
      
      JMP WAIT_INPUT

      
ENDLESS:
        JMP ENDLESS
CODE    ENDS
        END START
