;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Mon Sep 30 2024
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================

CODE    SEGMENT PUBLIC 'CODE'
        ASSUME CS:CODE

START:
        ; Write your code here
	MOV DX, 01H
	IN AL, DX
	
	MOV DX, 02H
	OUT DX, AL
ENDLESS:
        JMP ENDLESS
CODE    ENDS
        END START
