;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Sat Oct 5 2024
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================

DATA SEGMENT
   PORTA EQU 02H
   PORTB EQU 0F2H
   PORTC EQU 01H
DATA ENDS

CODE SEGMENT
   MOV AX, DATA
   MOV DS, AX
   
   ORG 0000H

START:
   MOV DX, PORTC
   IN AL,DX
   
   MOV DX, PORTA
   OUT DX, AL
   
   JMP START

CODE    ENDS
END
