;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Sat Oct 5 2024
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================

DATA SEGMENT
   PORTA EQU 0F0H
   PORTB EQU 0F2H
   PORTC EQU 0F4H
DATA ENDS

CODE SEGMENT
   MOV AX, DATA
   MOV DS, AX
   
   ORG 0000H

START:
   READ_PORTC:  
      MOV DX, PORTC
      IN AL, DX
   
   CMP AL, 01H
   JE RUNNING_LED
   CMP AL, 02H
   JE BCD_COUNTER
 
   CALL CLEAR_PORTA
   CALL CLEAR_PORTB
   
   JMP READ_PORTC
   
   RUNNING_LED:
   CALL CLEAR_PORTB
   
   MOV DX, PORTA
   
      DISP:
     MOV AL, 00000001B
     OUT DX, AL
     MOV AL, 00000010B
     OUT DX, AL
     MOV AL, 00000100B
     OUT DX, AL
     MOV AL, 00001000B
     OUT DX, AL
     MOV AL, 00010000B
     OUT DX, AL
     MOV AL, 00100000B
     OUT DX, AL
     MOV AL, 01000000B
     OUT DX, AL
     MOV AL, 10000000B
     OUT DX, AL
     JMP READ_PORTC
      
   BCD_COUNTER:
      CALL CLEAR_PORTA
      
      MOV DX, PORTB
      MOV AL, 00H
      
      _LOOP:
     CMP AL, 0AH
     JE READ_PORTC
     OUT DX, AL
     INC AL
     JMP _LOOP

CLEAR_PORTA:
   MOV DX, PORTA
   MOV AL, 00H
   OUT DX,AL
   RET

 CLEAR_PORTB:
   MOV DX, PORTB
   MOV AL, 00H
   OUT DX,AL 
   RET
   
HERE:
   NOP
   JMP HERE

CODE    ENDS
END
