;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Sun Oct 6 2024
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================

DATA SEGMENT
   PORTA EQU 0F0H
   PORTB EQU 0F2H
   PORTC EQU 0F4H
   COM_REG EQU 0F6H
DATA ENDS

CODE    SEGMENT PUBLIC 'CODE'
        ASSUME CS:CODE

START:
   MOV DX, COM_REG
   MOV AL, 10001001B
   OUT DX, AL
   
   MOV BH, 00H
   MOV BL, 01H
   
   WAIT_INPUT:
      MOV DX, PORTC
      IN AL, DX
      TEST AL, 01H
      JZ WAIT_INPUT

   CONT:
      MOV AL, BL   
      MOV DX, PORTA
      OUT DX, AL
      MOV AL, BH
      MOV DX, PORTB
      OUT DX, AL
      
      INC BL
      
      CMP BL, 0AH
      JL WAIT_INPUT
      
      MOV BL, 00H
      INC BH
      
      CMP BH, 0AH
      JL WAIT_INPUT

      MOV BH, 00H
      
      MOV AL, BL   
      MOV DX, PORTA
      OUT DX, AL
      MOV AL, BH
      MOV DX, PORTB
      OUT DX, AL
      JMP WAIT_INPUT
   
ENDLESS:
        JMP ENDLESS
CODE    ENDS
        END START
