;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Mon Oct 14 2024
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================

DATA	SEGMENT
   PORTA EQU 501H	; 0101 0000 0001
   PORTB EQU 500H	; 0101 0000 0000
				        ; 0101 0000 000X
				        ; 1098 7654 3210
DATA	ENDS

STK	SEGMENT STACK
   DW 200 DUP(?)
STK	ENDS

CODE    SEGMENT PUBLIC 'CODE'
        ASSUME CS:CODE, DS:DATA, SS:STK

	ORG 0000H
	
	XOR AX, AX
	XOR BX, BX
	XOR CX, CX
	XOR DX, DX
	
START:
   WAIT_INPUT:
      MOV DX, PORTB
      IN AL, DX

      CMP AL, 001H
      JE _TOGGLE
      CMP AL, 002H
      JE _CYCLONE
      CMP AL, 004H
      JE _SNAKE
      
      MOV DX,  PORTA
      MOV AL, 00H
      OUT DX, AL     
      JMP WAIT_INPUT

   _TOGGLE:
      MOV DX, PORTA
      MOV AL, 0FFH
      OUT DX, AL
      ;MOV DX, PORTB
      ;IN AL, DX
      ;CMP AL, 001H
      ;JE _TOGGLE
      JMP WAIT_INPUT
      
   _CYCLONE:
      ; 1 2 3 4
      ; 5 6 7 8
      ; CCW = 1 2 5 6
      ; CC	  = 4 3 7 8
     
      ; 1ST		2ND	3RD	4TH		LOOP
      ; 1 0 0 1	0 1 1 0	0 0 0 0	0 0 0 0	
      ; 0 0 0 0	0 0 0 0	0 1 1 0	1 0 0 1
      MOV DX, PORTA
      MOV AL, 00001001B
      OUT DX, AL

      MOV AL, 00000110B
      OUT DX, AL

      MOV AL, 01100000B
      OUT DX, AL

      MOV AL, 10010000B
      OUT DX, AL
      
      ;MOV DX, PORTB
      ;IN AL, DX
      ;CMP AL, 002H
      ;JE _CYCLONE
      JMP WAIT_INPUT
      
   _SNAKE:
      ; 1 2 -> 2 3  -> 3 4 -> 4 8 -> 8 7 -> 7 6 -> 6 5 -> 5 1
      MOV DX, PORTA
      MOV AL, 00000011B
      OUT DX, AL
      
      MOV AL, 00000110B
      OUT DX, AL
      
      MOV AL, 00001100B
      OUT DX, AL
      
      MOV AL, 10001000B
      OUT DX, AL
      
      MOV AL, 11000000B
      OUT DX, AL
      
      MOV AL, 01100000B
      OUT DX, AL
      
      MOV AL, 00110000B
      OUT DX, AL
      
      ;MOV DX, PORTB
      ;IN AL, DX
      ;CMP AL, 004H
      ;JE _SNAKE
      JMP WAIT_INPUT

CODE    ENDS
        END START